= Spring Boot HTMX integration

https://htmx.org/[HTMX] can be used just fine with Spring Boot out of the box.
However, as a couple of examples have shown, it usually requires a bit of boilerplate code to be written on the server side.
This library attempts to remove that boilerplate code by providing a few Spring MVC extensions that make it easy to use Thymeleaf templates and template fragments as HTMX partials that allow updating multiple parts of an UI selectively.

[[features]]
== Features

* Conveniently bundles the HTMX WebJAR.
* API to logically define HTMX partials in WebMVC controllers.
* Spring Boot auto configuration to set up Spring MVC to automatically render `HtmxPartials` instances as Thymeleaf templates and fragments.

An example project implementing the canonical TodoMVC sample can be found link:htmx-spring-boot-examples/htmx-spring-boot-example-todomvc[here].

[[quickstart]]
== Quickstart

Add the library to your Spring MVC application:

[source, xml]
----
<dependencies>
  <dependency>
    <groupId>de.odrotbohm.playground</groupId>
    <artifactId>htmx-spring-boot</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  <dependency>
</dependencies>

<!-- For snapshot access -->

<repositories>
  <repository>
    <id>spring-snapshots</id>
    <url>https://repo.spring.io/snapshot</url>
  </repository>
</repositories>
----

If you haven't already, please make sure you also have the Spring Boot web starter included.

[source, java]
----
// Use @HtmxController if you want to avoid the headers clause for all handler methods
@PostMapping(path = "/", headers = Htmx.HTMX_HEADER + "=true")
HtmxPartials indexStream(Model model) {

  // times is a List<Long> System.currentTimeMillis() as elements.
  model.addAttribute("times", Arrays.asList(now()));

  return new HtmxPartials()
    .append("pings").with("index :: ping");
}
----

Note, how we return an instance of `HtmxPartials` instance that allows us to logically define which fragments we want to set up.
In this particular case we define exactly one partial but could accumulate more as well to update other parts of the page.
Spring MVC will render those in the format expected resolving the given Thymeleaf template or template fragment reference as actual payload.
I.e. a template snippet like this:

[source, html]
----
<div>
  <p>Ping times</p>
  <ol id="pings">
    <li data-th-fragment="ping" data-th-each="time : ${times}">[[${time}]]</li>
  </ol>
</div>
----

the response would look like this:

[source, xml]
----
<div id="pings" hx-swap-oob="beforeend">
  <li>123456789</li>
</div>
----

[[ideas]]
== Still open / ideas

* Dedicated WebFlux support?
* Improve the translation of `HtmxPartials` into a `View`.
We currently use a `HandlerInterceptor` but that has to guess about the case it is supposed to kick in quite a bit.
A `HandlerMethodReturnValueHandler` looks like a better alternative.
However, decorating the existing list of them is rather cumbersome: post process all `RequestMappingHandlerAdapters`, wrap the ones contained in the adapter in a `HandlerMethodReturnValueHandlerComposite`, decorate that and set that back on the `RMHA`.
* Anything else? Please file an issue!

[[references]]
== Contributors and references

* https://htmx.org/[HTMX]
